### ISSUE TITLE
Todoist showing incorrect items in lists

### ISSUE THREAD

**Issue by rachelhannah123** [dakboard/bugs#10]
Dakboard displays tasks that have been assigned to other people and therefore DONT appear in the Today list on the app. When I select the Today list on the Dakboard it pulls these tasks assigned to other people through which is wrong. Please prioritise this as it renders my current use of Dakboard for Todoist useless as my screen is cluttered up with tasks not meant for me

**Comment by rachelhannah123** [comment]
Alternatively, allow filtered Todoist lists to be selected on Dakboard rather than just Projects. Then I could filter the tasks to the right ones myself and only display what’s relevant .

**Comment by cocarrig** [comment]
Hi,

Reviewing our ticket created in our ITSM system, I have confirmed this issue is resolved.  If you have any other questions or issues please reach out to support@dakboard.com.
