### ISSUE TITLE
Image widget not displaying web image

### ISSUE THREAD

**Issue by Mohoganogan** [dakboard/bugs#11]
I have been using the image widget to display a regional radar.  Some time in the last week it stopped working.  It now only displays all black.

https://icons.wxug.com/data/weather-maps/radar/united-states/salina-kansas-region-current-radar-animation.gif

**Comment by danking6** [comment]
@Mohoganogan Thanks for submitting. Looks like this was a temporary outage with WeatherUnderground. It seems to be resolved now. Please take another look and let us know if you're still running into issues. Thanks.
