### ISSUE TITLE
Swedish translation when using the News block

### ISSUE THREAD

**Issue by default80** [dakboard/bugs#12]
When using the News block with timestamp activated, the timestamp is not correctly translated into Swedish. I've found two cases so far. The first one is the string "one hour ago", which is not translated at all. It should state "en timme sedan". The second case is when the item was published less than an hour ago. For example, "32 minutes ago" is translated into "32 5 minuter sedan". The extra "5 " should be removed.

EDIT: Hardly ever used, but also the string "years ago" should be "år sedan".

**Comment by danking6** [comment]
@default80 thanks for submitting this. We've fixed these issues and the update should be released soon!
