### ISSUE TITLE
After upgrading my account I still can't change the photo timeout

### ISSUE THREAD

**Issue by jpcjpc69** [dakboard/bugs#13]
I upgraded to the essential plan to get access to both more layout tools, additional calendars and finally to shorten the photo timeout.  However, each time I try to do a timeout faster than 2 minutes, it shows me an error saying I have to upgrade.   This is frustrating.  :(

I'm using google chrome on a mac to set it up.  Please investigate.

**Comment by danking6** [comment]
This has been fixed. Closing this issue.
