### ISSUE TITLE
Last Month Calendar Days are not Dimmed

### ISSUE THREAD

**Issue by leemicw** [dakboard/bugs#15]
Currently my calendar shows July and August since the month just flipped over.  It looks like the logic to mark dates in the past has a small flaw.  In the attachment you can see the July dates are not dimmed and the past August dates are.  Earlier this week the dates in July were dimmed as expected.  It looks like the July dates are missing the dim css class.  I have included a picture of the issue and the html source. 

![dakboardCalendarDim](https://user-images.githubusercontent.com/2442577/62912003-07f26100-bd4c-11e9-9717-eba57e4d64e4.png)

**Comment by cocarrig** [comment]
Sorry to hear of the issues you have reported.  If you are still encountering issues with the calendar date dimming please reach out to use at contact@dakboard.com.
