### ISSUE TITLE
Using Scheduled Text, if you set a gradient, it doesn't honor time window

### ISSUE THREAD

**Issue by jpcjpc69** [dakboard/bugs#16]
Steps: 
1-add a scheduled text block to your screen
2-add text and set it to display at current time
3-preview /test and you'll see it works.
4-set it to display at a later time (not current time)
5-preview and you'll see it's gone.
6-now edit the block and set the background and gradient.
7-preview
Result: You'll see the background and gradient all the time, but the text won't be there.
EXPECTED: The entire block shouldn't show up until the time window.  You'd likely never need to have the background without the text.

**Comment by cocarrig** [comment]
Hi,

I have performed the steps you have provided to recreate this issue and can confirm this is resolved.  If you are still experiencing issue please reach out to contact@dakboard.com
