### ISSUE TITLE
google photos videos won't play

### ISSUE THREAD

**Issue by jpcjpc69** [dakboard/bugs#17]
I'm wondering how we can set Dakboard to automatically play the google videos in my google photos account?  Is there a way to set this up?  It's not obvious.  We have photos and videos in our google photos account.

**Comment by cocarrig** [comment]
This has been accounted for in both of the following requests open at this time:
https://github.com/dakboard/feature-requests/issues/370
https://github.com/dakboard/feature-requests/issues/266

Closing this bug case at this time
