### ISSUE TITLE
Only one scheduled text block works at a time

### ISSUE THREAD

**Issue by eknee** [dakboard/bugs#19]
I have two scheduled text blocks on my screen but only one will show the content at a time.  I was able to prove this out by disabling one scheduled block and enabling another.  When both displayed it doesn't work.

![image](https://user-images.githubusercontent.com/6667779/63231633-2214bf00-c1e4-11e9-8437-e7d85541039e.png)
![image](https://user-images.githubusercontent.com/6667779/63231644-32c53500-c1e4-11e9-9c7e-931d2fbdd07f.png)
![image](https://user-images.githubusercontent.com/6667779/63231649-52f4f400-c1e4-11e9-99fb-794be8510993.png)
![image](https://user-images.githubusercontent.com/6667779/63231661-96e7f900-c1e4-11e9-86ac-96704b31f215.png)
![image](https://user-images.githubusercontent.com/6667779/63231663-a6674200-c1e4-11e9-99b9-67a78a2cc0c9.png)

**Comment by danking6** [comment]
@eknee, thanks for the information. It looks like you may have duplicated the scheduled text block to create the "Daily Tasks" block. When duplicating the block, the schedule IDs remained the same as the first block, which causes an issue in our system. We'll see if we can add a fix for this in the future when duplicating scheduled text blocks.

In the meantime, please deleted and (manually) recreate one of the scheduled text blocks and it should work just fine from there. 

Thanks again for pointing this out and our apologies for the issues!

**Comment by eknee** [comment]
Ah interesting!  Thanks for the quick response.
