### ISSUE TITLE
Issue with Loops - Overlapping Screens

### ISSUE THREAD

**Issue by WSLabor** [dakboard/bugs#20]
We are running a loop with 3 screens.  The loop generally runs as expected, but after a few hours, the screens in the loop begin to overlap with each other.  This causes the "next screen" in the rotation to overlap a portion of the screen currently showing.  This happens with each screen as the loop transitions. (In other words, the 2nd screen overlaps a portion of the 1st screen while the 1st screen is showing; then, when the loop moves to the 2nd screen, only part of it is showing, while part of the 3rd screen overlaps the 2nd screen.  This continues on as the loop rotates between each screen.

**Comment by snapmags** [comment]
Having the same issue.

**Comment by bm29700** [comment]
I'm having the same issue.  Only seems to be a problem when looping 3 screens.

**Comment by cocarrig** [comment]
Hi,

If you are still experiencing this issue after refreshing your browser, please reach out to us at contact@dakboard.com so that we can gather more details on your configuration.
