### ISSUE TITLE
Animated Weather GIFs not working

### ISSUE THREAD

**Issue by aplovette1** [dakboard/bugs#22]
The Photo URL linked to a weather gif stopped working. If I go to the link in another window it works just fine, but it is not showing up in the DAKBoard screen.
Thanks!
![2019-09-12 12_51_54-DAKboard Options](https://user-images.githubusercontent.com/55251467/64804216-66ce1480-d55c-11e9-99af-857092078df6.png)
![2019-09-12 12_52_04-DAKboard Options](https://user-images.githubusercontent.com/55251467/64804218-66ce1480-d55c-11e9-940a-6c9a5433133b.png)
![2019-09-12 12_52_28-DAKboard](https://user-images.githubusercontent.com/55251467/64804219-66ce1480-d55c-11e9-97ba-3aabfec45773.png)

**Comment by danking6** [comment]
Yes, this was a temporary outage with weatherUnderground. You may need to grab a new URL from weather underground though. We have instructions on our support site here: https://dakboard.freshdesk.com/support/solutions/articles/35000062105
