### ISSUE TITLE
Darksky sunrise/sunset shows wrong time

### ISSUE THREAD

**Issue by TheLion** [dakboard/bugs#23]
The Darksky plugin shows the wrong time for sunrise and sunset. 

(Timezone issue perhaps?) It currently shows (at 09:00 in the morning) that sunrise will be at 12:46. 

Already checked and re- applied the timezone settings. 

When selecting OpenWeatherMap the correct sunrise/sunset is shown (sunset at 19:46 in my case).

**Comment by rangerdavid** [comment]
Happening for me too. I am on Pacific Time, and sunrise is showing Eastern Time (3 hours off/incorrect)

**Comment by cocarrig** [comment]
Hi,

If you are still experiencing this issue please review the timezone configuration locations in DAKboard below:
https://dakboard.freshdesk.com/support/solutions/articles/35000099598-how-to-set-the-timezone

If you are still having issues please reach out to contact@dakboard.com.

**Comment by rangerdavid** [comment]
Great, thanks. I will double check if this is still an issue.

Dave

________________________________________________________________________

**Comment by TheLion** [comment]
It now shows the correct sunrise/sunset time, but I'm curious what happens when we exit DST.
