### ISSUE TITLE
Can't customise CSS for twitter block?

### ISSUE THREAD

**Issue by DeanoAus** [dakboard/bugs#26]
Hey guys,
No matter how I attempt to add custom CSS to my screen to change the font of the twitter widget, it just will not apply? 

Am I missing something here?

```
.SandboxRoot.env-bp-970 .timeline-Tweet-text {
    font-size: 20;
    line-height: 25px;
    font-weight: 300;
    color: white;
}
```

Yet when displayed on my portrait screen, the font is huge and dynamic.

**Comment by danking6** [comment]
@DeanoAus thanks for submitting this. We are using the embed widget directly from Twitter, and unfortunately there's no way to apply CSS to the Twitter embed widget. If the font is too large, you may want to try shrinking the width of the block or changing the font size of the screen in the screen settings.

**Comment by DeanoAus** [comment]
Ah nuts, I thought the custom CSS would be loaded after and override the embed.

Thanks for the reply. :)
