### ISSUE TITLE
Update not happening within 2 minutes as advertised

### ISSUE THREAD

**Issue by holtehus** [dakboard/bugs#28]
Our DAKboard does not always update within 2 minutes as advertised. At least once a week I wait about 15 minutes for my changes to get through, but nothing happens and the only solution is to cut power to the DAKboard cpu and let it reboot, after which it pulls the updated content. This is at best beta performance for a service we pay for. Please help me resolve this issue. Kind regards, Kim (kim@holte-hus.dk)

**Comment by holtehus** [comment]
What, no one else experiencing very long refresh times?

**Comment by Keefe67** [comment]
We are having the same issues.  I work in a school and have 9 screens up, this worked once or twice now it's slowly updating.

**Comment by cocarrig** [comment]
Hi,

Content will update at the schedule shown on our website for configured boards:
dakboard.com/pricing

Changes made to your DAKboard screens will update at the following frequency:
**Predefined Screen**
Free: Checks for changes every 6 hours
Essential: Checks for changes every 2 minutes
Plus/Pro: Checks for changes every 15 minutes, Instant refresh when clicking “Refresh Displays” buttonCustom 

**Screens**
Free: N/A
Essential: Checks for changes every 2 minutes
Plus/Pro: Checks for changes every 15 minutes, Instant refresh when clicking “Refresh Displays” button

If you are still experiencing this issue on DAKboard please reach out to support@dakboard.com.  A member of support team can gather additional detail and compose a bug issue or help to identify a configuration issue by working with you on your account.
