### ISSUE TITLE
Fix Overlapping Weather Icons

### ISSUE THREAD

**Issue by m3891** [dakboard/bugs#30]
In the image below, the "sunset" icon overlaps today's "high" temperature number. I'm running DAKboard on my Raspberry Pi. I also noticed the same problem when I opened DAKboard on my Mac in Google Chrome. The only way to fix it on the Mac was if I made the screen bigger. Since I can't do that on the Raspberry Pi (the screen is already full size), something must be done to prevent the overlap. If I'm missing something, let me know. I'm assuming (though I don't know anything about programming) that it would be an easy fix by making the calendar more responsive to various screen sizes.

![69576859-2bf44e00-0f9b-11ea-9575-d82ec1b4a750](https://user-images.githubusercontent.com/58191063/69734563-2d3d8c00-10fd-11ea-8358-2431883eb03f.png)

**Comment by cocarrig** [comment]
Hi,

If you are still experiencing this issue on DAKboard please reach out to support@dakboard.com.  A member of support team can gather additional detail and compose a bug issue or help to identify a configuration issue by working with you on your account.
