### ISSUE TITLE
Google Nest Not Authenticating

### ISSUE THREAD

**Issue by theseanodell** [dakboard/bugs#31]
Nest Integration for accounts that have been migrated to Google Nest authentication are not working properly. Unable to authenticate and utilize feature.

**Comment by cocarrig** [comment]
Hi,

integration with google is pending their approval at this time.  We will update the following Github issue as soon as that status changes:
https://github.com/dakboard/feature-requests/issues/974

If you have any questions please reach out to support@dakboard.com
