### ISSUE TITLE
Some items in ical feed not showing on DAK board

### ISSUE THREAD

**Issue by WavMakR** [dakboard/bugs#33]
I have been a premium subscriber to DAKboard for a few years now.  I am having an issue with one of the ical feeds setup on the board.
http://www.mvihockey.org/ical_feed?tags=5286356

I  imported this into google calendar to look at it in more detail myself.

I am wondering if there is something that DAK is not handling specific events because the item is a 'game' tag instead of an 'event' tag.

Doesn't work from this feed:
https://sportsengine.page.link/?al%3Dsportsengine%253A%252F%252Fgame%252F27193729%253Fevent_start_time%253D2019-12-19T01%25253A50%25253A00Z%2526game_event_id%253D456445411%2526team_ids%25255B%25255D%253D172946%26apn%3Dcom.sportngin.android%26ct%3DiCalEventLink%26ibi%3Dcom.ngin.sport.iphone%26isi%3D499597400%26link%3Dhttp%253A%252F%252Fwww.mvihockey.org%252Fgame%252Fshow%252F27193729%253Fresource_id%253D456445411%2526start_time%253D2019-12-19T01%25253A50%25253A00Z%2526subseason%253D640325%2526team_ids%25255B%25255D%253D172946%2526type%253Dgame%26pt%3D319609%26utm_campaign%3DiCalEventLink&sa=D&ust=1577032811659000&usg=AOvVaw1JXR_JZNpV7PATLEERlYsh

Works fine from this feed:

https://sportsengine.page.link/?al%3Dsportsengine%253A%252F%252Fevent%252F456532703%253Fevent_start_time%253D2019-12-18T02%25253A00%25253A00Z%2526team_ids%25255B%25255D%253D172946%26apn%3Dcom.sportngin.android%26ct%3DiCalEventLink%26ibi%3Dcom.ngin.sport.iphone%26isi%3D499597400%26link%3Dhttp%253A%252F%252Fwww.mvihockey.org%252Fevent%252Fshow%252F456532703%253Fresource_id%253D456532703%2526start_time%253D2019-12-18T02%25253A00%25253A00Z%2526team_ids%25255B%25255D%253D172946%2526type%253Devent%26pt%3D319609%26utm_campaign%3DiCalEventLink&sa=D&ust=1577032811659000&usg=AOvVaw0O_GKiWYnSAW8pm2yPQFEe

The effect is that all of the practices and other events show up fine on DAK but none of the games, which of course are the most important.

Any help on this would be appreciated, thanks again for your help.

WavMakR

**Comment by WavMakR** [comment]
I noticed when I added this event to my Gmail calendar that start and end time are the same too, maybe that is tripping up DAK board.

**Comment by cocarrig** [comment]
Hi,

I have been unable to reproduce these issues due to the links no longer being valid.  If you are still experiencing this issue on DAKboard please reach out to support@dakboard.com.  A member of support team can gather additional detail and compose a bug issue or help to identify a configuration issue by working with you on your account.

**Comment by WavMakR** [comment]
This issue still persists.

Here is a new example, it happens when in agenda view and when the event
has just a start time or same start and end time.

http://www.mvihockey.org/ical_feed?tags=5945140

On 1/23 there is an event @7:50pm that does not show in agenda view when
displayed with other calendars.

RUSS
