### ISSUE TITLE
Sonos Integration

### ISSUE THREAD

**Issue by EricSch** [dakboard/bugs#34]
Can't add Sonos to my account.
When I try to authorize; I get until the Confirm Screen on Sonos. When I click Ok, I get redirected to the dakboard main page, but no Sonos account is listed in dakboard.
Seems like it isn't authorized.

Thanks

**Comment by cocarrig** [comment]
Hi,

If you are still experiencing this issue on DAKboard please reach out to support@dakboard.com.  A member of support team can gather additional detail and compose a bug issue or help to identify a configuration issue by working with you on your account.
