### ISSUE TITLE
4K with photos transition with 5 min transitions crashes web page after period of time

### ISSUE THREAD

**Issue by ryan8382** [dakboard/bugs#35]
When using the  my screen is is set to 1080p everything works fine. When the unit is set to anything above it will crash after some time. The time period can vary. I have it set to 1hr and it seems to be stable at that interval. I have not tried to go lower.

**Comment by Blue-Label** [comment]
Having the same issue, also notice the lightning bolt and temp icons in the corners when this happens. Haven't had this issue before and seems to have started in the past few weeks. There have been no changes to my setup, Pi mounted on the back of a TV on a wall. Seems to be some king of memory leak or something. Even swapped my PI out with another spare one I had but still having the issue. I just changed my timer to 30 minutes, lets see what happens. I'm on Dakboard version 2.14, not sure if upgrading to 2.16 will help or not. Can support please advise?

**Comment by perrymw08** [comment]
My pi zero w is extremely slow to load, the picture transitions are set at 2 min, and will routinely crash after about 90 minutes.

**Comment by cocarrig** [comment]
Hi,

If you are still experiencing this issue on DAKboard please reach out to support@dakboard.com.  A member of support team can gather additional detail and compose a bug issue or help to identify a configuration issue by working with you on your account.
