### ISSUE TITLE
Recurring Events not being displayed

### ISSUE THREAD

**Issue by oc1991** [dakboard/bugs#36]
When using Microsoft Authenticated calendar, dakboard fails to display some recurring events.
We tried using ical but when a recurring event is modified, dakboard will display the original event and the same event with whatever changes were applied.

**Comment by cocarrig** [comment]
Hi,

If you are still experiencing this issue on DAKboard please reach out to support@dakboard.com.  A member of support team can gather additional detail and compose a bug issue or help to identify a configuration issue by working with you on your account.
