### ISSUE TITLE
Changes broke font sizes

### ISSUE THREAD

**Issue by xomnia** [dakboard/bugs#37]
I have been away for a couple of weeks, and came back to my dakboard screen having all font sizes changed.  Trying to update the CSS using either classes or IDs seems to have stopped working, and also many blocks are not obeying changes to the "formatting" tab in the dakboard edit interface.  My calendar block in particular has serious font size issues and seems to be ignoring all changes I try to make.  What changed recently?

**Comment by cocarrig** [comment]
Hi,

If you are still experiencing this issue on DAKboard please reach out to support@dakboard.com.  A member of support team can gather additional detail and compose a bug issue or help to identify a configuration issue by working with you on your account.
