### ISSUE TITLE
Appointment times are incorrect

### ISSUE THREAD

**Issue by wisewoof** [dakboard/bugs#38]
Recently all appointment times shown by dakboard calendar are off by 1 hour.  I thought it was due to daylight savings but my timezone does not observe daylight savings. I confirmed my timezone is set correctly in dakboard.  Please help.

**Comment by cocarrig** [comment]
Hi,

Timezone can be set in more than one location, if you are still experiencing this issue please review the following article and reach out to contact@dakboard.com:
https://dakboard.freshdesk.com/support/solutions/articles/35000099598-how-to-set-the-timezone
