### ISSUE TITLE
Font too dark.

### ISSUE THREAD

**Issue by tonyrking** [dakboard/bugs#41]
Fault where font is shown too dark.
<img width="200" alt="Screenshot 2020-06-09 at 09 53 52" src="https://user-images.githubusercontent.com/59649152/84127557-57babb00-aa37-11ea-8836-7be0a685051b.png">

**Comment by cocarrig** [comment]
Hi Tony,

Stop on by the following blog article that may help explain options for changing configured fonts and colors in DAKboard, can if you are still having issues please contact us at contact@dakboard.com:
https://blog.dakboard.com/background-colors-gradients-titles-and-more-new-formatting-options/
