### ISSUE TITLE
Entries wrap around too much, filling screen.

### ISSUE THREAD

**Issue by tonyrking** [dakboard/bugs#42]
Entries will fill not truncate and fill a date cell of any length.
Needs to be truncated to one line or optional length.
<img width="325" alt="Screenshot 2020-06-09 at 09 56 09" src="https://user-images.githubusercontent.com/59649152/84127856-abc59f80-aa37-11ea-8ff6-e2db5f57539b.png">

**Comment by cocarrig** [comment]
Hi Tony,

Sorry you are seeing this.  For many of our clients they desire the data to not be truncated or reduced and are able to meet there needs by resizing of the display or screen.  If you would like to reach out to us at contact@dakboard.com we can help to explain a few solutions with you.

If you have concise expectations for an enhancement that you think will strike a balance for both users needs, please submit at the below link:
https://github.com/dakboard/Cloud-Platform/issues/new/choose
