### ISSUE TITLE
OneDrive and Google Drive photos JS stops loading

### ISSUE THREAD

**Issue by joshbenner** [dakboard/bugs#44]
After some time (hours or days), photos layer using Google Drive or One Drive (not sure if any other providers) will stop working, throwing a 404 when attempting to load a JS file. This results in the photos not appearing.

These attempted work arounds _do not_ work:
1. Refresh screen
2. Shift-reload browser

I've been able to work around this by editing the photo, changing the directory and immediately changing it back.

**Comment by cocarrig** [comment]
Sorry to hear you are running into issues Josh.  Often we find this is an issue network speed of the the device displaying DAKboard or the size of the photos are too large to load in time.  If you are still experiencing this issue please reach out to us at support@dakboard.com.
