### ISSUE TITLE
Not Launching "A secure connection is recommended"

### ISSUE THREAD

**Issue by awesomehaze** [dakboard/bugs#46]
I installed the DAKboard app on my kindle fire through the amazon app store. When I launch the app it throws the error: "A secure connection is recommended to use this app. We were unable to establish a secure connection and recommend that you try again later." Thanks for the help!

**Comment by cocarrig** [comment]
Sorry to hear you are running into this issue.  You can contact out support team at contact@dakboard.com if you're still experiencing this issue we would be glad to help you.
