### ISSUE TITLE
Up Next calendar displaying events from earlier in the day when Future items only is selected

### ISSUE THREAD

**Issue by rachelhannah123** [dakboard/bugs#5]
The Up Next item is correct but previous events are still showing as next in the list when they happened in the past and Future Events Only box is selected.

The “future events only” box is greyed out as non-selectable when Up Next mode is selected so it’s not like I could toggle between future events showing or not anyway.

I’ve emailed Dakboard support about this if you need further information

**Comment by cocarrig** [comment]
Hi,

I have reviewed this issue reported and indicated that a resolution was shared from contact@dakboard.com.  If you need any further assistance please let us know by reaching out again.
