### ISSUE TITLE
Emojis do not display - only blank box where emojis should be

### ISSUE THREAD

**Issue by rachelhannah123** [dakboard/bugs#6]
I have raised this several times via Dakboard support, dating back to 9 April and was advised there was a glitch in Dakboard software and that it should be added back in in the next few days.

**Comment by SSNDemon** [comment]
We have a fix for emojis but have not sent the update currently. We plan to have the emoji fix/update by next week.

**Comment by rachelhannah123** [comment]
Hi, I’ve been advised this in the past and it didn’t happen - not sure the item should be closed when a fix hasn’t been rolled out yet?
