### ISSUE TITLE
Double Asterisk bolding of characters sometimes fails on refresh

### ISSUE THREAD

**Issue by SSNDemon** [dakboard/bugs#8]
Continuation of an issue with bolding of characters on refresh here: https://github.com/dakboard/feature-requests/issues/447

**Comment by cocarrig** [comment]
Hi,

I have been unable to recreate this bug at this time, using multiple text boxes (with asterisk and without).

If you are still experiencing this issue on DAKboard please reach out to support@dakboard.com.  A member of support team can gather additional detail and compose a bug issue or help to identify a configuration issue by working with you on your account.
